---
title: "GetSigGenes-META"
author: "Jason Torres"
date: "August 4, 2016"
output:
  pdf_document:
    toc: yes
  html_document:
    fig_caption: yes
    highlight: textmate
    number_sections: yes
    theme: journal
    toc: yes
---

# Set-up project 

```{r setup, echo=FALSE}
library("data.table")
library("dplyr")
library("ggplot2")
#source("http://bioconductor.org/biocLite.R")
#biocLite("qvalue")
library("qvalue")
"%&%" <- function(a,b) paste0(a,b) 
server.dir <- "input_files/" 
root.dir <- server.dir %&% "meta/"
diag.dir <- server.dir %&% "diag/"

```


```{r gc_functions, echo=FALSE}

calc_lambda <- function(p.vec){
  #http://genometoolbox.blogspot.com/2014/08/how-to-calculate-genomic-inflation.html  
  chisq <- qchisq(1-na.omit(p.vec),1)
  lambda <- median(chisq)/qchisq(0.5,1)
  return(lambda)
}

gc_adjust <- function(z.vec,p.vec){
  lambda <- calc_lambda(p.vec)
  print("Inflation factor: " %&% lambda)
  z.adj.vec <- z.vec/sqrt(lambda)
  chi.vec <- z.adj.vec^2  
  p.adj.vec <- pchisq(chi.vec,1,lower.tail=FALSE)  
  return(list(z.adj.vec,p.adj.vec))
}

```


# Functions for Getting Bonferroni and FDR 5%-significant Gene Sets 

```{r sigfunct, echo=FALSE}

get.bonfer.genes <- function(file.vec,myalpha){
  top.vec <- c() 
  for (file in file.vec){
    ref.dir <- diag.dir 
    tissname <- gsub(".meta.txt","",file)
    ref.df <- fread(ref.dir %&% tissname %&% ".zscores.csv")
    keep.genes <- unique(ref.df$gene_name)
    
    result.file <- res.dir %&% file
    res.df <- fread(result.file) %>% tbl_df %>% arrange(ss.pvalue) %>% filter(Gene %in% keep.genes)
    ## Genomic Control Correction
    gc_adjust_list <- gc_adjust(res.df$ss.zscore,res.df$ss.pvalue)
    res.df$ss.zscore <- gc_adjust_list[[1]]
    res.df$ss.pvalue <- gc_adjust_list[[2]]
    alpha <- 0.05
    bonfer <- alpha / dim(res.df)[1]
    bonfer.df <- res.df %>% filter(ss.pvalue < bonfer,more.significant=="TRUE")
    top.vec <- append(top.vec,bonfer.df$Gene)
  }
  return(top.vec)
}

get.fdr.genes <- function(file.vec,myalpha){
  top.vec <- c() 
  for (file in file.vec){
    ref.dir <- diag.dir 
    tissname <- gsub(".meta.txt","",file)
    ref.df <- fread(ref.dir %&% tissname %&% ".zscores.csv")
    keep.genes <- unique(ref.df$gene_name)
    
    result.file <- res.dir %&% file
    df <- fread(result.file)
    df <- filter(df, Gene %in% keep.genes)
    df <- na.omit(df)
    ## Genomic Control Correction
    gc_adjust_list <- gc_adjust(df$ss.zscore,df$ss.pvalue)
    df$ss.zscore <- gc_adjust_list[[1]]
    df$ss.pvalue <- gc_adjust_list[[2]]
    qval <- qvalue(df$ss.pvalue)$qvalues 
    df <- cbind(df,qval)
    fdr <- 0.05
    fdr.df <- df %>% filter(qval < fdr,more.significant=="TRUE") %>% arrange(qval)
    top.vec <- append(top.vec,fdr.df$Gene)
  }
  return(top.vec) 
}
```

# Partitioning Top Gene Sets 

```{r top_gene_partitioning, echo=FALSE,fig.height=8,fig.weight=2}

rds.dir <- "intermediate_files/"
t2d.loci.df <- readRDS(rds.dir%&%"t2d.loci.df.RDS")
t2d.loci.genes <- unique(t2d.loci.df$nearby.gene)
reported.genes <- unique(t2d.loci.df$reported.gene)
t2d.loci.genes.unknown <- setdiff(t2d.loci.genes,reported.genes)

gene.partition <- function(gene.vec,criteria.name){
  # criteria.name should be "Bonferonni" or "FDR05"
  known.genes <- intersect(gene.vec,reported.genes)
  known.set <- rep("T2D.Gene",length(known.genes))
  df1 <- data.frame(known.genes,known.set)
  names(df1) <- c("Gene","Type")
  known.loci.genes <- intersect(gene.vec,t2d.loci.genes.unknown)
  known.loci.set <- rep("Known.Region",length(known.loci.genes))
  df2 <- data.frame(known.loci.genes,known.loci.set)
  names(df2) <- c("Gene","Type")
  new.loci.genes <- setdiff(gene.vec,c(known.genes,known.loci.genes))
  new.loci.set <- rep("Unknown",length(new.loci.genes))
  df3 <- data.frame(new.loci.genes,new.loci.set)
  names(df3) <- c("Gene","Type")
  df <- rbind(df1,df2,df3)
  Criteria <- rep(criteria.name,length(dim(df)[1]))
  df <- cbind(df,Criteria)
  return(df)
}

make.partition.plot <- function(alpha){
  b.df <- gene.partition(bonfer.genes,"Bonferonni")
  f.df <- gene.partition(fdr.genes,"FDR.05")
  df <- rbind(b.df,f.df)
  plt <- ggplot(data=df,aes(x=Criteria)) +
    geom_bar(aes(fill=Type),color="black") +
    scale_fill_brewer() + ylab("Count") + 
    xlab("Gene Set") + 
    ggtitle("Composition of MetaXcan-significant Gene Sets") +
    theme(plot.title = element_text(face="bold",size=20),
          axis.title.x = element_text(face="bold"),
          axis.title.y = element_text(face="bold")) +
    theme_bw()
  df2 <- filter(df,Criteria=="FDR.05"); df1 <- filter(df,Criteria=="Bonferonni")
  df2 <- df2[!duplicated(df2),]; df1 <- df1[!duplicated(df1),]
  if (alpha==1){
    saveRDS(df1,paste0(rds.dir,"lasso_Bonferonni.RDS"))
    saveRDS(df2,paste0(rds.dir,"lasso_FDR05.RDS"))
  } else if (alpha==0.5){
    saveRDS(df1,paste0(rds.dir,"elasticNet_Bonferonni.RDS"))
    saveRDS(df2,paste0(rds.dir,"elasticNet_FDR05.RDS"))    
  } else {
    print("Alpha can only be 1")
  }
  print("###### Bonferonni-Significant ########")
  print(filter(df1,Type=="T2D.Gene")$Gene)
  print(filter(df1,Type=="Known.Region")$Gene)
  print(filter(df1,Type=="Unknown")$Gene)
  print("###### FDR05-Significant ########")
  print(filter(df2,Type=="T2D.Gene")$Gene)
  print(filter(df2,Type=="Known.Region")$Gene)
  print(filter(df2,Type=="Unknown")$Gene)
  plt
}
```

# DIAGRAM-GERA Meta-Analyses 

```{r diag3, echo=FALSE}
rds.dir <- "intermediate_files/meta/"
dir.create(rds.dir)

res.dir <- root.dir 
file.vec <- list.files(res.dir,pattern="TW")
bonfer.genes <- unique(get.bonfer.genes(file.vec,"0.5"))
fdr.genes <- unique(get.fdr.genes(file.vec,"0.5"))
make.partition.plot(0.5)
```
