---
title: "02.4_GetSigGenes-GERA-Rep.Rmd"
author: "Jason Torres"
date: "August 4, 2016"
output:
  pdf_document:
    toc: yes
  html_document:
    fig_caption: yes
    highlight: textmate
    number_sections: yes
    theme: journal
    toc: yes
---

# Set-up project 

```{r setup, echo=FALSE}
library("data.table")
library("dplyr")
library("ggplot2")
#source("http://bioconductor.org/biocLite.R")
#biocLite("qvalue")
library("qvalue")
"%&%" <- function(a,b) paste0(a,b) 
#root.dir <- "/Volumes/im-lab/nas40t2/jason/projects/MetaXcan/results/"
rds.dir <- "intermediate_files/" 
```

# Functions for Getting significant Gene Set 

```{r sigfunct, echo=FALSE}

make_rep_df <- function(){
  g.vec <- c(); mod.vec <- c(); diagp.vec <- c(); gerap.vec <- c()
  eval.vec <- c(); type.vec <- c(); chrom.vec <- c(); diagz.vec <- c()
  geraz.vec <- c(); diagn.vec <- c(); geran.vec <- c()
  diag.df <- readRDS(rds.dir %&% "diag/sig.gene.TW.a05.df.RDS")
  diag.df <- diag.df[!duplicated(diag.df), ]
  load(rds.dir %&% "gera/metaXcan.results.Rdata")
  p.df <- cbind(select(p.EN.df,one_of("Gene","CrossTissue")),select(p.EN.df,contains("TW_")))
  z.df <- cbind(select(z.EN.df,one_of("Gene","CrossTissue")),select(z.EN.df,contains("TW_")))
  n.EN.df <- readRDS(rds.dir %&% "gera/n.EN.df.RDS")
  n.df <- cbind(select(n.EN.df,one_of("Gene","CrossTissue")),select(n.EN.df,contains("TW_")))
  # Iterate through rows (i.e. gene-tissue associations) 
  for (r in 1:dim(diag.df)[1]){ 
    gene <- diag.df[r,3]; model <- diag.df[r,9]; diagp <- diag.df[r,12]
    type <- diag.df[r,4]; chrom <- diag.df[r,6]; diagz <- diag.df[r,11]
    diagn <- diag.df[r,15]
    g.vec <- append(g.vec,gene)
    mod.vec <- append(mod.vec,model)
    diagp.vec <- append(diagp.vec,diagp)
    diagz.vec <- append(diagz.vec,diagz)
    type.vec <- append(type.vec,type)
    chrom.vec <- append(chrom.vec,chrom)
    diagn.vec <- append(diagn.vec,diagn)
    temp.df <- filter(p.df,Gene == gene) %>% select(one_of(model))
    if (dim(temp.df)[1] == 1){
      gerap <- temp.df[1,1] # ensures that only one value is extracted; ONLY ONE VALUE SHOULD BE RETURNED!
    } else {
      stop("More than one unique is returned from subsetting; please inspect!")
    }
    gerap.vec <- append(gerap.vec,gerap)
    temp.df <- filter(z.df,Gene == gene) %>% select(one_of(model))
    if (dim(temp.df)[1] == 1){
      geraz <- temp.df[1,1] # ensures that only one value is extracted; ONLY ONE VALUE SHOULD BE RETURNED!
    } else {
      stop("More than one unique is returned from subsetting; please inspect!")
    }
    geraz.vec <- append(geraz.vec,geraz)
    temp.df <- filter(n.df,Gene == gene) %>% select(one_of(model))
    if (dim(temp.df)[1] == 1){
      geran <- temp.df[1,1] # ensures that only one value is extracted; ONLY ONE VALUE SHOULD BE RETURNED!
    } else {
      stop("More than one unique is returned from subsetting; please inspect!")
    }
    geran.vec <- append(geran.vec,geran)
    if (!is.na(gerap) & gerap <= 0.05){
      eval <- TRUE 
    } else if (!is.na(gerap) & gerap > 0.05){
      eval <- FALSE
    } else{
      eval <- FALSE
    }
    eval.vec <- append(eval.vec,eval)
  }
  rep.df <- data.frame(g.vec,chrom.vec,type.vec,mod.vec,diagz.vec,
                       diagp.vec,diagn.vec,geraz.vec,gerap.vec,
                       geran.vec,eval.vec,stringsAsFactors=FALSE)
  names(rep.df) <- c("gene","chrom","type","model","diag.z.score","diag.p.value",
                     "diag.num.used.snps","gera.z.score","gera.p.value",
                     "gera.num.used.snps","replicated")
  saveRDS(rep.df,rds.dir %&% "diag/sig.genes.gera-rep.df.RDS")
  print("Saved RDS File")
  return(rep.df)
}

```

# Partitioning Top Gene Sets 

```{r top_gene_partitioning, echo=FALSE,fig.height=8,fig.weight=2}
#t2d.loci.df <- fread("/Volumes/im-lab/nas40t2/jason/projects/MetaXcan/results/t2d-gene-info.txt")
t2d.loci.df <- readRDS(rds.dir%&%"t2d.loci.df.RDS")
t2d.loci.genes <- unique(t2d.loci.df$nearby.gene)
reported.genes <- unique(t2d.loci.df$reported.gene) 
t2d.loci.genes.unknown <- setdiff(t2d.loci.genes,reported.genes)

gene.partition <- function(gene.vec,criteria.name){
  # criteria.name here is P-value < 0.05 in GERA Study 
  known.genes <- intersect(gene.vec,reported.genes)
  known.set <- rep("T2D.Gene",length(known.genes))
  df1 <- data.frame(known.genes,known.set)
  names(df1) <- c("Gene","Type")
  known.loci.genes <- intersect(gene.vec,t2d.loci.genes.unknown)
  known.loci.set <- rep("Known.Region",length(known.loci.genes))
  df2 <- data.frame(known.loci.genes,known.loci.set)
  names(df2) <- c("Gene","Type")
  new.loci.genes <- setdiff(gene.vec,c(known.genes,known.loci.genes))
  new.loci.set <- rep("Unknown",length(new.loci.genes))
  df3 <- data.frame(new.loci.genes,new.loci.set)
  names(df3) <- c("Gene","Type")
  df <- rbind(df1,df2,df3)
  Criteria <- rep(criteria.name,length(dim(df)[1]))
  df <- cbind(df,Criteria)
  return(df)
}

make.partition.plot <- function(alpha){
  rep.df <- gene.partition(rep.genes,"Pvalue < 0.05 in GERA Study")
  df <- rep.df
  plt <- ggplot(data=df,aes(x=Criteria)) +
    geom_bar(aes(fill=Type),color="black") +
    scale_fill_brewer() + ylab("Count") + 
    xlab("Gene Set") + 
    ggtitle("Composition of MetaXcan-significant Gene Sets") +
    theme(plot.title = element_text(face="bold",size=20),
          axis.title.x = element_text(face="bold"),
          axis.title.y = element_text(face="bold")) +
    theme_bw()
  if (alpha==1){
    saveRDS(df,paste0(rds.dir,"lasso_gera-replicated.df.RDS"))
  } else if (alpha==0.5){
    saveRDS(df,paste0(rds.dir,"elasticNet_gera-replicated.RDS"))
  } else {
    print("Alpha should be either 0.5 or 1")
  }
  print("###### Significant ########")
  print(filter(df,Type=="T2D.Gene")$Gene)
  print(filter(df,Type=="Known.Region")$Gene)
  print(filter(df,Type=="Unknown")$Gene)
  plt
}
```

# GERA Analyses 

```{r gera, echo=FALSE}
rep.genes <- unique(filter(make_rep_df(),replicated==TRUE)$gene)
make.partition.plot(0.5)
```
