---
title: "LocusTable.Rmd"
author: "Jason Torres"
date: "October 31, 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

```{r setup, echo=FALSE}

library("dplyr")
library("grid")
library("ggplot2")
library("gridExtra")
library("data.table")
"%&%" <- function(a,b) paste0(a,b) 

root.dir <- "/Users/jtorres/Google Drive/Projects/MetaXcan/MetaXcanT2D/"

rds.dir <- root.dir %&% "RDS.gtexV6p/"
fig.dir <- root.dir %&% "figures.gtexV6p/" 
ggd.ref.df <- readRDS(paste0(rds.dir,"ggd.ref.df.RDS"))
#load(paste0(rds.dir,"diag3/metaXcan.results.Rdata"))
lw.df <- readRDS(rds.dir%&%"lw.rep.df.RDS")
lw.df <- select(lw.df,one_of("gene","model","diag.z","diag.p",
                             "gera.z","gera.p","gw.p05"))
lw.df$model <- gsub("TW_","",lw.df$model)
lw.df$model <- gsub("_","-",lw.df$model)
lw.df$diag.z <- prettyNum(lw.df$diag.z,digits=3)
lw.df$diag.p <- prettyNum(lw.df$diag.p,digits=3)
lw.df$gera.z <- prettyNum(lw.df$gera.z,digits=3)
lw.df$gera.p <- prettyNum(lw.df$gera.p,digits=3)


```


```{r get_T2D_genes, echo=FALSE}

file.dir <- "/Users/jtorres/Google Drive/Projects/MetaXcan/MetaXcanT2D/"
rds.dir <- file.dir %&% "RDS.gtexV6p/"
ggd.df <- readRDS(rds.dir%&%"ggd.ref.df.RDS")
rep.genes <- unique(readRDS(rds.dir %&% "loci.df.RDS")$reported.gene)
loci.df <- readRDS(rds.dir%&%"loci.df.RDS")
ebi.dir <- "/Volumes/im-lab/nas40t2/jason/projects/ReferenceData/NHGRI/"
ebi.file <- ebi.dir %&% "nhgri_ebi-trait-genes.txt.gz"

ebi.df <- fread("cat " %&% ebi.file %&% " | zmore")
names(ebi.df)<-c("trait","genes")
ebi.df <- filter(ebi.df,trait=="Type_2_diabetes")
ref.vec <- c()
for (r in ebi.df$genes){
  vec <- strsplit(r,",_")[[1]]
  ref.vec <- append(ref.vec,vec)
}
ref.vec <- unique(ref.vec)
rep.genes <- unique(append(rep.genes,ref.vec))

```


Make Chrom Vector 

```{r make_chrom_vec, echo=FALSE}

get_chrom <- function(genename){
  chrom <- na.omit(as.numeric(filter(ggd.ref.df,symbol==genename)$chr))[1]
}

make_chrom_vec <- function(){
  vec <- c()
  for (g in lw.df$gene){
    c <- get_chrom(g)
    vec <- append(vec,c)
  }
  return(vec)
}

chr <- make_chrom_vec()

lw.df <- cbind(chr,lw.df)

```



Table functions

```{r table_functions, echo=FALSE}

edit_cell <- function(table, row, col, name="core-fg", ...){
  #http://stackoverflow.com/questions/32173928/r-tablegrob-change-format-of-row
  row <- row + 1 # my adjustment 
  col <- col + 1 # my adjustment
  l <- table$layout
  ids <- which(l$t %in% row & l$l %in% col & l$name==name)
  for (id in ids){
  newgrob <- editGrob(table$grobs[id][[1]], ...)
  table$grobs[id][[1]] <- newgrob
  }
  table
}

mytheme <- gridExtra::ttheme_default(
  core = list(fg_params=list(cex = 0.7),
              bg_params=list(fill="ghostwhite",alpha=0.3,col="black")),
  colhead = list(fg_params=list(cex = 0.9),
                 bg_params=list(alpha=0.30,col="black")),
  rowhead = list(fg_params=list(cex = 0)))   

```


Plot Function  

```{r save_plot_func, echo=FALSE}


save_lwstat_plot <- function(start,stop,fname){
  lw.df$gw.p05[is.na(lw.df$gw.p05)] <- FALSE
  temp.df <- lw.df[(start:stop),]
  rep.vec <- (1:dim(temp.df)[1])[temp.df$gw.p05]
  temp.df <- temp.df[,1:7]
  names(temp.df) <- c("Chr","Gene","Model","DIAGRAM\nZ-score",
                    "DIAGRAM\np-value","GERA\nZ-score",
                    "GERA\np-value")
  novel.vec <- (1:dim(temp.df)[1])[!(temp.df$Gene %in% rep.genes)]
  tabgrob <- tableGrob(temp.df,
                      theme=mytheme)
  tabgrob <- edit_cell(tabgrob, row=rep.vec, col=7, "core-bg", 
                  gp=gpar(fill="firebrick1",alpha=0.8,
                          col = "firebrick4", lwd=6))
  tabgrob <- edit_cell(tabgrob, row=novel.vec, col=2, "core-bg", 
                  gp=gpar(fill="dodgerblue1",alpha=0.8, 
                          col = "dodgerblue4", lwd=3))
  plt <- grid.arrange(tabgrob,nrow=1,ncol=1)
  ggsave(filename=fname,plot=plt,width=8,height=15)
}

```


```{r save_plots, echo=FALSE}

save_lwstat_plot(1,40,fig.dir%&%"lw-stat-tab.p1.pdf")
save_lwstat_plot(41,80,fig.dir%&%"lw-stat-tab.p2.pdf")
save_lwstat_plot(81,120,fig.dir%&%"lw-stat-tab.p3.pdf")
save_lwstat_plot(121,160,fig.dir%&%"lw-stat-tab.p4.pdf")
save_lwstat_plot(161,196,fig.dir%&%"lw-stat-tab.p5.pdf")

```

