---
title: "ExtractResults-T2DLoci.Rmd"
author: "Jason Torres"
date: "August 23, 2016"
output:
  pdf_document:
    toc: yes
  html_document:
    fig_caption: yes
    highlight: textmate
    number_sections: yes
    theme: journal
    toc: yes
---


```{r setup}

"%&%" <- function(a,b) paste0(a,b) 

library("data.table")
library("dplyr")


root.dir <- "/Users/jtorres/Google Drive/Projects/MetaXcan/MetaXcanT2D/"
rds.dir <- root.dir %&% "RDS.gtexV6p/"
t2d.loci.df <- readRDS(rds.dir%&%"t2d.loci.df.RDS")

load(rds.dir%&%"diag3/metaXcan.results.Rdata")

```


Append Z-scores 


```{r append_z_scores}

make_t2d_loci_z_df <- function(){
  mods <- names(z.EN.df)[2:length(names(z.EN.df))]
  out.df <- t2d.loci.df
  for (mod in mods){
    print(mod) 
    z.vec <- c() 
    for (i in 1:dim(t2d.loci.df)[1]){
      g <- t2d.loci.df[i,]$nearby.gene
      z <- as.numeric(filter(z.EN.df,Gene==g) %>% dplyr::select(one_of(mod)))
      z.vec <- append(z.vec,z) 
    }
    out.df <- cbind(out.df,z.vec)
    names(out.df)[length(names(out.df))] <- mod
  }
  return(out.df)
}

t2d.loci.z.df <- make_t2d_loci_z_df()
saveRDS(t2d.loci.z.df,file=rds.dir%&%"diag3/t2d.loci.z.df.RDS")

```


