---
title: "06.4_AppendGTExInfo.Rmd"
author: "Jason Torres"
date: "September 20, 2016"
output:
  pdf_document:
    toc: yes
  html_document:
    fig_caption: yes
    highlight: textmate
    number_sections: yes
    theme: journal
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Add GTEx information 

Before running code below, complete these steps first: 

* VPN to tarbell server (UChicago)
* run 06.3_getGTEx_eQTL.runjobs.py (in the tarbell.dir directory)
* cat *.pred.gtex.txt > mtxn-sig.pred.gtex.txt
* vim mtxn-sig.pred.gtex.txt and insert this header:
  rsid  pos chrom model ensid gtex.id tss.distance  pval.nominal  slope slope.se

```{r setup, echo=FALSE}

"%&%" <- function(a,b) paste0(a,b)

library("data.table")
library("dplyr")

tarbell.dir <- "/Volumes/im-lab/nas40t2/jason/projects/MetaXcan/results/predictors/gtexV6p/"
file.dir <- "/Users/jtorres/Google Drive/Projects/MetaXcan/MetaXcanT2D/"
rds.dir <- file.dir %&% "RDS.gtexV6p/"

```

```{r append_gtex_eqtls, echo=FALSE}

modsnp.df <- readRDS(file=rds.dir %&% "mtxnsig-gene-pred.df.RDS")

gtex.df <- as.data.frame(fread("cat " %&% tarbell.dir %&% "mtxn-sig.pred.gtex.txt.gz" %&% " | zmore"))

append_gtex_eqtl <- function(){
  gtex.id <- c()
  gtex.beta <- c()
  gtex.se <- c()
  gtex.p <- c() 
  tss.distance <- c() 
  for (i in 1:dim(modsnp.df)[1]){
    rs <- modsnp.df[i,4]
    mod <- modsnp.df[i,2]
    eid <- modsnp.df[i,3]
    temp.df <- filter(gtex.df,rsid==rs,model==mod,ensid==eid)
    if (dim(temp.df)[1]==0){
      gtex.id <- append(gtex.id, NA)
      gtex.beta <- append(gtex.beta, NA)
      gtex.se <- append(gtex.se, NA)
      gtex.p <- append(gtex.p, NA)      
      tss.distance <- append(tss.distance, NA) 
    } else{
      gid <- temp.df[1,6]
      gb <- temp.df[1,9]
      gse <- temp.df[1,10]
      gp <- temp.df[1,8]
      tss <- temp.df[1,7]
      gtex.id <- append(gtex.id, gid)
      gtex.beta <- append(gtex.beta, gb)
      gtex.se <- append(gtex.se, gse)
      gtex.p <- append(gtex.p, gp)
      tss.distance <- append(tss.distance, tss)
    }
  }
  out.df <- cbind(modsnp.df,gtex.id,gtex.beta,gtex.se,gtex.p,tss.distance)
  out.df$gtex.id <- as.character(out.df$gtex.id)
  return(out.df)
}

modsnp.gtex.df <- append_gtex_eqtl()
saveRDS(modsnp.gtex.df, file=rds.dir %&% "modsnp.gtex.df.RDS")

# Investigate Missing SNPs 
miss.df <- filter(modsnp.gtex.df,is.na(gtex.id))
saveRDS(miss.df, file=rds.dir %&% "miss.df.RDS")


```



