---
title: "GTEx_SOX4_check.Rmd"
author: "Jason Torres"
date: "August 26, 2016"
output: pdf_document
---

```{r setup}

"%&%" <- function(a,b) paste0(a,b)

library("dplyr")
library("data.table")
library("ggplot2")

root.dir <- "/Volumes/im-lab/nas40t2/Data/dbGaP/GTEx/"
v6p.path <- root.dir %&% "V6p-gtexportal/GTEx_Analysis_v6p_eQTL_expression_matrices/" %&% "Muscle_Skeletal_Analysis.v6p.normalized.expression.bed.gz"

v6.path <- root.dir %&% "V6p-gtexportal/V6/" %&% "Muscle_Skeletal_Analysis.expr.txt"

v6p.df <- fread("cat " %&% v6p.path %&% " | zmore")

v6.df <- fread(v6.path)

```


```{r sox4 }

v6p.sox4 <- filter(v6p.df,gene_id=="ENSG00000124766.4")
id.vec <- names(v6p.sox4)[5:dim(v6p.sox4)[2]]
ex.vec <- as.numeric(v6p.sox4[5:dim(v6p.sox4)[2]])
p.df <- as.data.frame(cbind(id.vec,ex.vec))
p.df$id.vec <- as.character(p.df$id.vec)
p.df$ex.vec <- as.numeric(p.df$ex.vec)


v6.sox4 <- filter(v6.df,Id=="ENSG00000124766.4")
names(v6.sox4)[1] <- "gene_id"
id.vec <- names(v6.sox4)[2:dim(v6.sox4)[2]] 
ex.vec <- as.numeric(v6.sox4[2:dim(v6.sox4)[2]])
m.df <- as.data.frame(cbind(id.vec,ex.vec))
m.df$id.vec <- as.character(m.df$id.vec)
m.df$ex.vec <- as.numeric(m.df$ex.vec)

sox.df <- inner_join(m.df,p.df,by="id.vec")
```


```{r comparison}

plt1 <- ggplot(data=sox.df,aes(x=ex.vec.x)) + 
  geom_histogram(col="black",fill="dodgerblue1",binwidth=5,alpha=0.5) + 
  geom_histogram(data=sox.df,aes(x=ex.vec.y),
                 col="black",fill="black",binwidth=5,alpha=0.2); plt1

plt2 <- ggplot(data=sox.df,aes(x=ex.vec.x,y=ex.vec.y)) + geom_point(); plt2

filter(sox.df,ex.vec.x<50,ex.vec.y>150)
filter(sox.df,ex.vec.x>150,ex.vec.y<50)

cor.test(sox.df$ex.vec.x,sox.df$ex.vec.y)

ks.test(sox.df$ex.vec.x,sox.df$ex.vec.y)

```

