---
title: "Manuscript_Check"
author: "Jason Torres"
date: "January 17, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

There are 196 locus-widesignficant gene-level associations
There are 79 uniquelocus-wide significant genes:


```{r setup_env, echo=FALSE}

"%&%" <- function(a,b) paste0(a,b)

library("data.table")
library("dplyr")

file.dir <- "/Users/jtorres/Google Drive/Projects/MetaXcan/MetaXcanT2D/"
rds.dir <- file.dir %&% "RDS.gtexV6p/"

```


Lookup number of tests  


```{r}

load(rds.dir %&% "diag3/metaXcan.results.Rdata")
df <- readRDS(rds.dir %&% "diag3/sig.gene.TW.a05.bonfer.df.RDS")
genes <- p.EN.df$Gene
p.mat <- as.matrix(p.EN.df[,grepl("TW_",names(p.EN.df))])
row.names(p.mat) <- genes
length(na.omit(as.numeric(p.mat)))
```


FDR Check

```{r}

library("qvalue")
p.vec <- as.numeric(p.mat)
names(p.vec) <- rep(genes,45)
p.vec <- na.omit(p.vec)
q.vec <- qvalue(p.vec)$qvalues
sigs <- q.vec[q.vec <= 0.05]
length(unique(sigs)) # 150 FDR sig genes 

df.f <- readRDS(rds.dir %&% "T2Dcore.df.RDS")
df.b <- filter(df, diag.mult.correct==TRUE)
length(unique(df$gene))
f <- select(df.f,one_of("gene","type"))[!duplicated(f$gene),]
table(f$type) # known 37, T2D 25, unk 52
f$gene

```

